app/models.py
from . import db
from werkzeug.security import (generate_password_hash, check_password_hash)
from flask_login import UserMixin
from . import login_manager
from datetime import datetime


@login_manager.user_loader
def user_loader(user_id):
    return User.query.get(int(user_id))


class Blogpost(db.Model):

    __tablename__ = 'blogpost'
    id = db.Column(db.Integer, primary_key=True)
    blog_title = db.Column(db.String)
    post_blog_section = db.Column(db.Text)
    username = db.Column(db.String)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    comments = db.relationship(
        "Comments", backref="post_comments", lazy="dynamic")
    user = db.relationship('User', backref='user', lazy=True)

    def __init__(self, post_blog_section, blog_title, user_id):
        self.post_blog_section = post_blog_section
        self.blog_title = blog_title
        self.user_id = user_id

    def __repr__(self):
        return f"There is a pretty cool blog here !:{self.post_blog_section}"


class Comments(db.Model):

    __tablename__ = 'comments'
    id = db.Column(db.Integer, primary_key=True)
    comments_section = db.Column(db.Text)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    blogpost_id = db.Column(db.Integer, db.ForeignKey('blogpost.id'))

class HomeComments(db.Model):

    __tablename__ = 'homecomments'
    id = db.Column(db.Integer, primary_key=True)
    home_comments_title = db.Column(db.String)
    home_comments_section = db.Column(db.Text)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    full_name = db.Column(db.String(255))
    username = db.Column(db.String(255), unique=True)
    email = db.Column(db.String(255), unique=True, index=True)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    password_hash = db.Column(db.String(255))
    blog_post = db.relationship(
        "Blogpost", backref="user_blogs", lazy="dynamic")
    comments = db.relationship(
        "Comments", backref="user_comments", lazy="dynamic")
    home_comments = db.relationship("HomeComments", backref="userhomecomments", lazy ="dynamic" )

    @property
    def password(self):
        raise AttributeError("You cannot read the password attribute")

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return f'User {self.username}'

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import (StringField, TextAreaField,
                     SubmitField, SelectField, IntegerField)
from wtforms.validators import Required


class AddBlog(FlaskForm):
    title = StringField()
    blogpost = TextAreaField(
        "You seem like the type that can express themselves")
    submit = SubmitField('Add Blog')
    


class DelBlog(FlaskForm):
    id = IntegerField(
        "please enter the ID number of Blog you would like to delete ")
    submit = SubmitField("Remove Pitch")


class CommentsForm(FlaskForm):
    comment = TextAreaField("Don't be shy ! This is a free space...")
    submit = SubmitField("Submit Comment")


class DelComments(FlaskForm):
    id = IntegerField(
        "Please enter the ID number of the comment you would like to delete")

class UpdateBlog(FlaskForm):
    title = StringField()
    editblog = TextAreaField("edit blog here")
    submit = SubmitField("Edit Blog")
class HomeCommentsForm(FlaskForm):
    homecomment = TextAreaField("I know your brave enough")
    submit = SubmitField("Post Comment")

app/__init__.py
from flask import Flask
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_bootstrap import Bootstrap

db = SQLAlchemy()
login_manager = LoginManager()
# security level, monitor the changes in a user's request header and log the user out
login_manager.session_protection = "strong"
# We prefix the login endpoint with the blueprint name because it is located inside a blueprint.
login_manager.login_view = "auth.login"

bootstrap = Bootstrap()


def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    bootstrap.init_app(app)

    # Initializing flask extensions
    db.init_app(app)
    login_manager.init_app(app)

    # Registering the main app Blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # Registering auth blueprint
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix="/authenticate")

    # Setting requests config
    from .requests import configure_request
    configure_request(app)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint("main",__name__)

from . import views

app/main/views.py
from flask import (render_template, request, redirect, url_for, abort)
from . import main
from .forms import AddBlog, DelBlog, CommentsForm, UpdateBlog, HomeCommentsForm
from ..models import User, Blogpost, Comments, HomeComments
from flask_login import login_required, current_user
from .. import db


@main.route("/")
def index():

    blogposts = Blogpost.query.filter_by().all()

    return render_template('home.html', blogposts=blogposts)


@main.route("/about")
def about():
    return render_template('about.html')


@main.route("/add", methods=["GET", "POST"])
@login_required
def add_blog():
    form = AddBlog()
    if form.validate_on_submit():
        title = form.title.data
        blogpost = form.blogpost.data

        new_blogpost = Blogpost(
            blog_title=title, post_blog_section=blogpost, user_id=current_user.id)
        db.session.add(new_blogpost)
        db.session.commit()

        return redirect(url_for('main.blogs_list'))

    return render_template('add.html', form=form)


@main.route("/delete/<blog_id>", methods=["GET", "POST"])
@login_required
def del_blog(blog_id):

    blog = Blogpost.query.filter_by(id=blog_id).first()
    db.session.delete(blog)
    db.session.commit()

    return redirect(url_for('main.blogs_list'))


@main.route("/deletecomment/<int:blog_id>/<int:comments_id>", methods=["GET", "POST"])
@login_required
def del_comment(blog_id, comments_id):

    comments = Comments.query.filter_by(id=comments_id).first()
    db.session.delete(comments)
    db.session.commit()

    return redirect(url_for('main.comments', blogpost_id=blog_id))


@main.route('/blogs')
@login_required
def blogs_list():

    blogposts = Blogpost.query.filter_by(user_id=current_user.id)[::-1]
    return render_template('blogs.html', blogposts=blogposts)


@main.route("/comments/<int:blogpost_id>", methods=['GET', 'POST'])
def comments(blogpost_id):

    form = CommentsForm()

    if form.validate_on_submit():
        comment = form.comment.data

        new_comment = Comments(comments_section=comment,
                               user_id=current_user.id, blogpost_id=blogpost_id)
        db.session.add(new_comment)
        db.session.commit()

    all_comments = Comments.query.filter_by(blogpost_id=blogpost_id).all()
    title = 'blogpost'
    return render_template("comments.html", all_comments=all_comments, title=title, form=form, blogpost_id=blogpost_id)


@main.route("/viewblogs/<int:blogpost_id>")
def viewblogs(blogpost_id):
    blog = Blogpost.query.filter_by(id=blogpost_id).first()
    return render_template("singlepost.html", blog=blog)


@main.route("/editblogs/<int:blogpost_id>", methods=['GET', 'POST'])
def editblogs(blogpost_id):
    blog = Blogpost.query.filter_by(id=blogpost_id).first()
    form = UpdateBlog()

    if form.validate_on_submit():
        blog.blog_title = form.title.data
        blog.post_blog_section = form.editblog.data
        db.session.add(blog)
        db.session.commit()
        return redirect(url_for('main.viewblogs', blogpost_id=blog.id))

    all_edits = Blogpost.query.filter_by(id=blogpost_id).first()
    return render_template("editblogs.html", blog=blog, form=form)


# @main.route("/homecomments/<int:homecomments_id>", methods=['GET', 'POST'])
# def homecomments(homecomments_id):
#     comment = HomeComments.query.filter_by(id=homecomments_id).all()
#     form = HomeCommentsForm()

#     if form.validate_on_submit():
#         comment.home_comments_title = form.title.data
#         comment.home_comments_section = form.homecomment.data
#         db.session.add(comment)
#         db.session.commit()

#         return redirect(url_for('main.index', homecomments_id=comment.id))
#         all_home_comments = HomeComments.query.filter_by(
#             id=homecomments_id).all()

#         return render_template("home.html", comment=comment, form=form)

app/templates/about.html
{%extends "base.html"%}
{%block content%}

<div class="container">
    <div class="jumbotron" style="background-color: darkkhaki">
        <div class="card mb-4" style="background-color: olive">
            <h1 style="font-family: 'Rock Salt', cursive; color: white; text-align: center;">ABOUT US</h1>
            <p style="font-family: 'Rock Salt', cursive; color: white;">Blogs is an application that allows users to
                sign
                up, login, create and edit Blogs that they post on our
                webiste. Also a user is able view the comments made on his/her blog profile. The idead of blogs came
                about
                in order to give people a place they can air out their views in a safe environment.
                Everybody deserves the right to express themselves, It's only right that we provide them the best
                environment to do that.
                <ol style="font-family: 'Rock Salt', cursive; color: white;">
                    The technologies used to create the app are:
                    <li>psql</li>
                    <li>Visual studio code</li>
                    <li>SQLALCHEMY</li>
                    <li>python</li>
                </ol>
            </p>
        </div>
    </div>
</div>

{% endblock %}

app/templates/add.html
{% extends "base.html" %}
{% block content %}

<div class="jumbotron" style="background-color: olive">
    <h1 style=" font-family: 'Rock Salt', cursive; color: white;"> We want people who can express themselves. Show us
        what you got !</h1>
    <form style=" font-family: 'Rock Salt', cursive; color: white;" class="form-group" method="POST">
        {{form.hidden_tag()}}
        {{form.title.label}}{{form.title(class = "form-control")}}
        <br>
        {{form.blogpost.label}}{{form.blogpost(class="form-control")}}
        <br>
        {{form.submit(class="btn btn-block" )}}
    </form>
</div>

{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/styles.css')}}">
    <link href="https://fonts.googleapis.com/css?family=Rock+Salt&display=swap" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">

    </script>
</head>

<body style="background-color: darkgoldenrod;">
    <nav class="navbar" style="background-color: coral">
        <div class="navbar nav">
            <a class="nav-item nav-link" href="{{url_for('main.index')}}"
                style=" font-family: 'Rock Salt', cursive; color: white;">Home</a>
            <a class="nav-item nav-link" href="{{url_for('main.about')}}"
                style=" font-family: 'Rock Salt', cursive; color: white;">About us</a>
            <a class="nav-item nav-link" href="{{url_for('main.add_blog')}}"
                style=" font-family: 'Rock Salt', cursive; color: white;">Add Blog</a>
            <a class="nav-item nav-link" href="{{url_for('main.blogs_list')}}"
                style=" font-family: 'Rock Salt', cursive; color: white;">Blogs</a>
            <div class="collapse navbar-collapse">
                {%if current_user.is_authenticated%}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></a>
                    {%endif%}
                </li>
            </div>
            {%if current_user.is_authenticated%}
            <li class="nav-item dropdown" style=" font-family: 'Rock Salt', cursive; color: white;">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas "></i> Profile </a>
                <div class="dropdown-menu dropdown-menu-right dropdown-info "
                    aria-labelledby="navbarDropdownMenuLink-4">
                    <a class="dropdown-item"
                        href="{{url_for('main.index', id = current_user.id)}}">{{current_user.username}}</a>
                    <a class="dropdown-item" href="{{url_for('auth.logout')}}">Log out</a>
                </div>
            </li>
            {%else%}
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('auth.login')}}"
                    style=" font-family: 'Rock Salt', cursive; color: white;">Log In</a>
            </li>
            {%endif%}
            </ul>
        </div>
    </nav>
    {% block content%}

    {% endblock %}
</body>

</html>

app/templates/blogs.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h1 style=" font-family: 'Rock Salt', cursive; color: white;">These are all the blogs who have created</h1>
    {%for blogpost in blogposts%}
    <div class="card mb-4" style=" font-family: 'Rock Salt', cursive; color: white;">
        <div class="card-body" style="background-color: coral;">
            <h1>{{loop.index}}.{{blogpost.blog_title}}</h1>
            <p>{{blogpost.post_blog_section|truncate(40)}}...
            </p>
            <br>
            <a class="btn btn-primary" href="/viewblogs/{{blogpost.id}}" style="background-color: gray;">Read More</a>
            <a class="btn btn-primary" href="/delete/{{blogpost.id}}" style="background-color: gray;">Delete</a>
            <br>
            <a href="/comments/{{ blogpost.id }}" style="color: gray;">view comments/comment on Blog</a>

        </div>
    </div>
    {%endfor%}
</div>
{% endblock %}

app/templates/comments.html
{% extends "base.html" %}
{% block content %}

<div class="jumbotron" style="background-color: darkolivegreen;">

    <form style="font-family: 'Rock Salt', cursive; color: white; " method="POST">
        {{form.hidden_tag()}}
        {{form.comment.label}}
        <div style="display: flex;">
            {{form.comment()}}
            {{form.submit()}}
        </div>
    </form>
    {% for comment in all_comments %}
    <li style="font-family:  'Rock Salt', cursive; color: white;  ">
        {{comment.comments_section}}
        <a class="btn btn-primary" href="/deletecomment/{{blogpost_id}}/{{comment.id}}"
            style="background-color: gray;">Delete</a>
    </li>

    {% endfor %}

</div>

{% endblock %}

app/templates/delete.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
    <p> Would you like to delete one of the Blogs ?</p>
    <p>If so, please fill out their ID in order to remove them from the list</p>
    <form method="POST">
        {{form.hidden_tag()}}
        {{form.id.label}} {{form.id}}
        {{form.submit()}}
    </form>
</div>
{% endblock %}

app/templates/editblogs.html
{% extends "base.html" %}
{% block content %}

<div class="jumbotron" style="background-color: darkolivegreen">

    <form method="POST" class="form-group" style="font-family:  'Rock Salt', cursive; color: white;;">
        {{form.hidden_tag()}}
        {{form.title.label}}{{form.title(class='form-control', value=blog.blog_title)}}
        {{form.editblog.label}}{{form.editblog(class='form-control', value=blog.post_blog_section)}}
        <br>
        {{form.submit(class='btn btn-primary')}}
    </form>
</div>


{% endblock %}

app/templates/home.html
{%extends 'base.html'%}

{%block content%}
<div class="container" style="background-color: darkkhaki;">
    <div class="blogs">
        {% if current_user.is_authenticated %}
        {% for blogpost in blogposts %}
        <div class="blog">
            <div class="blog-header">
                <div class="jumbotron" style="background-color:olive">
                    <div class="card mb-4">
                        <div class="card-body" style="background-color: coral;">
                            <div class="blog-title" style="font-family: 'Rock Salt', cursive; color: white;">
                                {{ blogpost.blog_title }}</div>
                            <div class="blog-info" style="font-family: 'Rock Salt' , cursive; color: white;"> by
                                {{ blogpost.user.username }}</div>
                        </div>
                        <div class="blog-body" style="font-family: 'Rock Salt' , cursive; color: white; background-color: coral;">
                            {{ blogpost.post_blog_section[:75] + '...' }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br>
        {% endfor %}
        {% else %}
        <div class="container" style="background-color:mediumaquamarine">
            <div class="jumbotron" style="background-color: olive;">
                <div class="card mb-4" style="background-color: coral;">
                    <div class="card-body">
                        <h style=" font-family: 'Rock Salt', cursive; color: white;">Tesla CyberTruck</h1>
                            <p> The Cybertruck has arrived and it looks nothing like any pickup truck you've ever seen.
                                Tesla
                                CEO Elon Musk revealed the long-awaited electric pickup truck at its Design Studio in
                                Hawthorne, California, just outside Los Angeles.

                                When the truck initially drove onto the stage, many in the crowd clearly couldn't
                                believe that
                                this was actually the vehicle they'd come to see. The Cybertruck looks like a large
                                metal
                                trapezoid on wheels, more like an art piece than a truck.
                                The most expensive version of the truck, the Tri Motor All-Wheel-Drive, will be able to
                                carry
                                3,500 pounds, tow up to 14,000 pounds and go from zero to 60 in 2.9 seconds. It will
                                also be
                                able to drive up to 500 miles on a full charge. Base models will have a range of 250
                                miles.
                                In addition to being able to carry cargo in its bed, the truck will have lockable
                                storage
                                spaces under the hood and in the sides. The bed itself also has a sliding cover. Drivers
                                will
                                also be able to adjust the ride height of the truck, for when they are on the highway or
                                off-road, using an adaptive air suspension system.
                            </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="container" style="background-color:mediumaquamarine">
            <div class="jumbotron" style="background-color: olive;">
                <div class="card mb-4" style="background-color: coral; ">
                    <div class="card-body">
                        <h1 style=" font-family: 'Rock Salt', cursive; color: white;">HIV AIDS</h1>
                        <p style=" font-family: 'Rock Salt', cursive; color: white;"> Human immunodeficiency virus (HIV)
                            is a virus that attacks immune cells called CD4 cells,
                            which
                            are a type of T cell.

                            These are white blood cells that move around the body, detecting faults and anomalies in
                            cells
                            as well as infections. When HIV targets and infiltrates these cells, it reduces the body's
                            ability to combat other diseases.

                            This increases the risk and impact of opportunistic infections and cancers. However, a
                            person
                            can carry HIV without experiencing symptoms for a long time.

                            HIV is a lifelong infection. However, receiving treatment and managing the disease
                            effectively
                            can prevent HIV from reaching a severe level and reduce the risk of a person passing on the
                            virus.
                            AIDS is the most advanced stage of HIV infection. Once HIV infection develops into AIDS,
                            infections and cancer pose a greater risk.

                            Without treatment, HIV infection is likely to develop into AIDS as the immune system
                            gradually
                            wears down. However, advances in ART mean than an ever-decreasing number of people progress
                            to
                            this stage.

                            By the close of 2015, around 1,122,900 people were HIV-positive. To compare, figures from
                            2016
                            show that medical professionals diagnosed AIDS in an estimated 18,160 people.
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="container" style="background-color:mediumaquamarine">
            <div class="jumbotron" style="background-color: olive
            ">
                <div class="card mb-4" style="background-color: coral">
                    <div class="card-body">
                        <H1 style=" font-family: 'Rock Salt', cursive; color: white;">Liverpool grind out another win as
                            belief in Jurgen Klopp's men
                            grows
                        </H1>
                        <p style=" font-family: 'Rock Salt', cursive; color: white;"> Jurgen Klopp grinned, his bright
                            white teeth gleaming under the floodlights as he walked off
                            the
                            Anfield pitch thumping
                            the badge on his chest and soaking up the adulation of the fans in the stands. This was not
                            a
                            vintage Liverpool
                            performance, but it was a vital win and he knew it.

                            A couple of hours earlier, news of Jonjo Shelvey's late equaliser for Newcastle against
                            Manchester City had spread
                            across the stadium. Liverpool knew victory here would take them 11 points clear of their
                            rivals.
                            It was an opportunity
                            they were not expecting but one they had to take.
                            Virgil van Dijk's goals - two headers from Trent Alexander-Arnold deliveries in the space of
                            six
                            first-half minutes -
                            put them in a commanding position, a position from which it seemed they might run wild. But
                            Brighton refused to lie
                            down. When Alisson Becker was sent off and Lewis Dunk guided the resulting free-kick past
                            Adrian, it felt like Liverpool
                            might crumble.
                            According to Opta, Liverpool have now scored 40 goals from set pieces since the start of
                            last
                            season. It is more than
                            any other side in the Premier League. Van Dijk's towering frame can be impossible to defend
                            against and he is not their
                            only threat either. In the same time-frame, they have scored 29 headed goals. No other
                            Premier
                            League side has managed
                            more than 19.
                        </p>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

app/templates/homecomment.html
{%extends "base.html"}
{%block content%}


{%endblock%}

app/templates/singlepost.html
{% extends "base.html" %}
{% block content %}

<div class="container">
    <div class="jumbotron" style="background-color: darkkhaki; font-family:  'Rock Salt', cursive; color: white;">
        <h1 style=" font-family:  'Rock Salt', cursive; color: white;  ">{{blog.blog_title}}</h1>
    </div>

    <hr>
    <p style="font-family:'Rock Salt', cursive; color: white;">{{blog.post_blog_section}}</p>
    <a href="/editblogs/{{blog.id}}" method=post class="btn btn-link"
        style="font-family:  'Rock Salt', cursive; color: white;;">Edit</a>
</div>

{% endblock %}